name: 'dbt_hevo_project'
version: '1.0'
config-version: 2

profile: 'hevo_profile'

source-paths: ["models"]
target-path: "target"
clean-targets: ["target"]

vars:
  hevo_database: 'HEVO_DB'
  hevo_schema: 'HEVO_SCHEMA'

models:
  dbt_hevo_project:
    +materialized: view
