name: 'dbt_hevo'
version: '1.0.0'
profile: 'dbt_hevo'
target-path: "target"  # directory which will store compiled SQL files
clean-targets:
  - "target"
  - "dbt_modules"

models:
  dbt_hevo:
    +materialized: view  # or 'table' if you want to create tables
