version: 2

sources:
  - name: hevo_schema
    database: HEVO_DB  # Your Snowflake database name
    schema: HEVO_SCHEMA  # Your Snowflake schema name
    tables:
      - name: raw_customers
      - name: raw_orders
      - name: raw_payments
